on: [push]
name: build
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 10.x, 12.x, 14.x ]

    name: Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build assets
        run: |
          # By compiling both `Main.elm` and `Worker.elm`, we make sure all
          # intermediate files are present before `npm run prod` runs.
          #
          # Otherwise, parcel would compile both files in parallel which can
          # lead to data races and let one of the compiler processes fail with
          # an error about corrupt files.
          npx elm make app/elm/Main.elm --output /dev/null
          npx elm make app/elm/Worker.elm --output /dev/null
          npm run prod

      - name: Check formatting
        run: |
          npx elm-format --validate app/elm tests
          npx prettier --check "app/js/*.js"
